[package]
name = "nunchi-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "nunchi 데스크톱 앱"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
nunchi-core = { path = "../nunchi-core" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
